Update build push action - add deployment

diff --git a/.github/workflows/build_push.yml b/.github/workflows/build_push.yml
--- a/.github/workflows/build_push.yml
+++ b/.github/workflows/build_push.yml
@@ -36,10 +36,12 @@ jobs:
       - name: Set buildkit pod name
         id: buildkit_pod
         run: echo "::set-output name=pod_name::front-buildkit-${{ github.run_number }}"
+      - name: Generate image's name based on tag and date
+        id: image_name
+        run: echo "::set-output name=tag::frontend:${{ steps.date.outputs.date }}_${{ github.run_number }}"
       - name: Kubectl apply buildkit pod
         run: |
           cat infra_front/build-agents/buildkit/pod.yaml | sed "s|{{POD_NAME}}|${{ steps.buildkit_pod.outputs.pod_name }}|" | kubectl apply -f -
-        
       - name: Build image
         run: |
           kubectl wait --timeout=300s --for=condition=Ready pod/${{ steps.buildkit_pod.outputs.pod_name }} -n build-agents-dev 
@@ -51,9 +53,20 @@ jobs:
                     --local dockerfile=. \
                     --local context=/tmp/bcontext \
                     --frontend-opt filename=tmp/bcontext/Dockerfile.prod \
-                    --output type=image,\"name=nexus.nexus-dev.svc.cluster.local:5056/bowelsound/frontend:${{ steps.date.outputs.date }}_${{ github.run_number }},nexus.nexus-dev.svc.cluster.local:5056/bowelsound/frontend:latest\",push=true \
-                    --export-cache type=inline \
-                    --import-cache type=registry,ref=nexus.nexus-dev.svc.cluster.local:5056/bowelsound/frontend:latest
-          kubectl delete pod -n build-agents-dev ${{ steps.buildkit_pod.outputs.pod_name }}
-            
+                    --output type=image,\"name=nexus.nexus-dev.svc.cluster.local:5056/bowelsound/frontend:${{ steps.image_name.name }},nexus.nexus-dev.svc.cluster.local:5056/bowelsound/frontend:latest\",push=true \
+                    # --export-cache type=inline \
+                    # --import-cache type=registry,ref=nexus.nexus-dev.svc.cluster.local:5056/bowelsound/frontend:latest
+          retVal=$?
 
+          if [ $retVal -ne 0 ]; then
+              echo "Error when generating image"
+              kubectl logs ${{ steps.buildkit_pod.outputs.pod_name }} -n build-agents-dev --tail 1000 && kubectl delete pod -n build-agents-dev ${{ steps.buildkit_pod.outputs.pod_name }}
+              exit 1
+          fi
+          kubectl delete pod -n build-agents-dev ${{ steps.buildkit_pod.outputs.pod_name }}
+          
+      - name: Apply new deployment
+        run : |
+          sed "s|{{IMAGE_NAME}}|${{ steps.image_name.name }}|" infra_front/k8s_front/k8s/deployment.yaml | kubectl apply -f -
+          kubectl rollout restart deployment/bowelsound-frontend -n bowelsound-dev
+          kubectl rollout status deployment/bowelsound-frontend -n bowelsound-dev --timeout=300s
